### ISSUE TITLE
7.9.x jar download

### ISSUE THREAD

**Issue by pszabo75** [sonar-scala/sonar-scala#681]
Where can I get the 7.9.x LTE jar file? Bintray URLs seem to be broken.

**Comment by mwz** [comment]
Hi, all new releases starting from 8.7 go to Sonatype and Maven Central, but I haven't re-published any of the historical versions. The 7.9 LTE series have now reached the EOL since we have a new SonarQube 8.9 LTS out, so I'll be publishing a new version of sonar-scala for the new LTS version soon. If for some reason you really want the version for the old LTS plugin, you can still get it from the Docker image (tag 4.2.0, `/opt/sonarqube/extensions/plugins/sonar-scala-plugin-7.9.0.jar`) https://hub.docker.com/r/mwizner/sonarqube-scala-plugins.
You don't get support for Scala 2.13 in the old LTS series of sonar-scala, so I'd recommend switching to the latest available version or waiting a little bit for the new LTS release - hope that helps.

**Comment by pszabo75** [comment]
Thank you for the quick answer. We just started to upgrade our plant from 6.7 to 7.9.
I'll try to extract the jar file from the docker image.
